baseURL = 'https://example.com/'
languageCode = 'zh-cn'
title = 'My Hugo Blog'

[params]
  description = 'A blog powered by Hugo'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
